apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: gateway
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - interval: 30s
    port: http
    path: /metrics
  