apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
stringData:
  ACCESS_TOKEN_SECRET: 3248yhuiyf8372hui832@#$324
  ACCESS_TOKEN_EXPIRY: 15m
  REFRESH_TOKEN_SECRET: dsafew234dsfe34cjgreut387278
  REFRESH_TOKEN_EXPIRY: 7d