apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    release: "stable"
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/mongodb
